### ISSUE TITLE
Engine needs more documentation

### ISSUE THREAD

**Issue by becega** [LabVIEW-DCAF/StandardEngine#36]
There is no documentation on the engine or in the VIs on the engine. WHne Chriss was trying to understand how the engine worked he mentioned there is no documentation on it. @Beazurt

**Comment by dsmithni** [comment]
now needs even more

**Comment by dsmithni** [comment]
@Beazurt  "More comments in the engine code.  We are recommending this to advanced users.  Advanced users want to look at the code to understand what it does.  Doesn't need to be perfect or super detailed, but just add some comments to help people navigate the engine."

**Comment by Beazurt** [comment]
Just made another pass. Most VIs now have their VI documentation updated to reflect the new behavior (no more wrong documentation!).  I also added some breadcrumbs to help lead people from the open function to where most of the execution code actually occurs. Still not good enough to close this, but I feel better about it.

**Comment by dsmithni** [comment]
yay
