### ISSUE TITLE
Optionally Allow Multiple Writers When Mapping Process Channels

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/StandardEngine#6]
The engine configuration class currently prevents any possibility of multiple writers to any tag.  I still think this is the right default behavior as multiple writers makes it much easier to create configuration errors.  There is also no reason to ever have multiple inputs write to the same tag. 

In some cases, it might be nice to allow multiple writers to the same tag in the case of process functions.  If implemented, a tag would be allowed to have one input writer AND one or more process writers.  This would be a setting that could be turned on our off in the configuration class.

**Comment by becega** [comment]
There should not be more than one module writing to the a Tag, To do that there should be a Explicit effort to do it, using a module like the tag select. If it is needed the engine could be extended with a child class of the Standard engine but the standard engine shoudl not allow this.
