### ISSUE TITLE
Make error options control look pretty

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/StandardEngine#61]
This doesn't seem to fit with the rest of the UI theme.

Make it prettier, please.

![image](https://cloud.githubusercontent.com/assets/5288961/23135096/d2d723a0-f75c-11e6-9a1f-b38a71568630.png)

**Comment by smithed** [comment]
I dunno it looks rugged and dependable like error options should. They don't need no fancy checkmarks.

**Comment by pollockm** [comment]
The fix was just to make the background lighter.  About as trivial of a change as it gets.
