### ISSUE TITLE
Add "iteration start time" tag based on the High Resolution Relative Seconds VI

### ISSUE THREAD

**Issue by ryanpopo** [LabVIEW-DCAF/StandardEngine#64]
Moving this issue from TagEditorCore as it was mistakenly created there.

Some upcoming modules based around C code will need to have an idea of when the current iteration of the engine began executing based on an absolute time value, which the High Resolution Relative Seconds provides. It would be nice if this start time could be published as a tag so that modules could then reference it for their own use.

**Comment by smithed** [comment]
you should probably look into what this function uses for a timebase and also be sure to identify to any users what you are providing. For iteration start time I would expect a timestamp or the tick counter (or micro-tick). I'm also not sure what tradeoffs there are for that functio vs normal tick counts (if any).

**Comment by Beazurt** [comment]
Implemented in 66e8ca6
