### ISSUE TITLE
One of the latest commits (3/7/2017) causes unexpected behavior

### ISSUE THREAD

**Issue by ryanpopo** [LabVIEW-DCAF/StandardEngine#67]
After installing build 99 of the Standard Engine, Shared Memory Module (SMM) crashes LabVIEW RT. Upon debugging the issue, I found that after the SMM's init.vi is called, its close.vi is called for some reason, all before the input/process/output VIs are executed. This was causing the shared memory files to be removed and all of the pointers to be invalidated.

After downgrading back to build 97 from Feb 23rd, the issue went away. Then upgrading back to build 99, the issue returned.

**Comment by ryanpopo** [comment]
Correction, I rolled back to build 96 (there is no 97).

**Comment by pollockm** [comment]
Oops.  Previous commit worked in some cases, not all.  Fixing.
