### ISSUE TITLE
Use Module Timing Source UI Doesn't Properly Update from Config.

### ISSUE THREAD

**Issue by Beazurt** [LabVIEW-DCAF/StandardEngine#68]
The last selected module is shown instead of what is saved in the config object.

**Comment by Beazurt** [comment]
Closed in 6a6c5c0

**Comment by Beazurt** [comment]
Apparently if there are multiple engines that use this feature, some of the engines may not save the selected value properly. Only the first target in the configuration uses the right value at runtime. This issue is currently only partially fixed.

**Comment by jwgorman** [comment]
wasn't auto closed because of and syntax. Closing
